export type ProductCategory =
  | "Baju Cotton"
  | "Sukan & Sublimation"
  | "Uniform & Workwear"
  | "Kelengkapan";

export type Product = {
  id: string;
  code: string;
  name: string;
  category: ProductCategory;
  price: number;
  priceLabel: string;
  image: string;
  specs?: string[];
};

export const productCategories: ProductCategory[] = [
  "Baju Cotton",
  "Sukan & Sublimation",
  "Uniform & Workwear",
  "Kelengkapan",
];

export const catalogueProducts: Product[] = [
  {
    id: "baju-cotton",
    code: "BJK-001",
    name: "Baju Cotton",
    category: "Baju Cotton",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/baju-cotton.png",
    specs: ["Round neck", "Sesuai untuk event, sekolah, dan komuniti"],
  },
  {
    id: "baju-cotton-premium",
    code: "BJK-002",
    name: "Baju Cotton Premium",
    category: "Baju Cotton",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/baju-cotton-premium.png",
    specs: ["Material lebih selesa", "Sesuai untuk corporate gift dan uniform casual"],
  },
  {
    id: "baju-cotton-kanak-kanak",
    code: "BJK-003",
    name: "Baju Cotton Kanak-Kanak",
    category: "Baju Cotton",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/baju-cotton-kanak-kanak.png",
    specs: ["Saiz kanak-kanak", "Sesuai untuk sekolah dan family day"],
  },
  {
    id: "baju-cotton-long-sleeve",
    code: "BJK-004",
    name: "Baju Cotton Long Sleeve",
    category: "Baju Cotton",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/baju-cotton-long-sleeve.png",
    specs: ["Lengan panjang", "Sesuai untuk uniform dan aktiviti luar"],
  },
  {
    id: "baju-oversized",
    code: "BJK-005",
    name: "Baju Oversized",
    category: "Baju Cotton",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/baju-oversized.png",
    specs: ["Cutting oversized", "Sesuai untuk merch dan lifestyle apparel"],
  },
  {
    id: "baju-polo",
    code: "BJK-006",
    name: "Baju Polo",
    category: "Uniform & Workwear",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/baju-polo.png",
    specs: ["Kolar polo", "Sesuai untuk staf, event, dan corporate wear"],
  },
  {
    id: "baju-microfiber",
    code: "BJK-007",
    name: "Baju Microfiber",
    category: "Sukan & Sublimation",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/baju-microfiber.png",
    specs: ["Material ringan", "Sesuai untuk sukan, hiking, dan event outdoor"],
  },
  {
    id: "baju-microfiber-half-zip",
    code: "BJK-008",
    name: "Baju Microfiber Half Zip",
    category: "Sukan & Sublimation",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/baju-microfiber-half-zip.png",
    specs: ["Half zip", "Sesuai untuk pasukan dan aktiviti luar"],
  },
  {
    id: "baju-jersey",
    code: "BJK-009",
    name: "Baju Jersey",
    category: "Sukan & Sublimation",
    price: 0,
    priceLabel: "Harga ikut design",
    image: "/images/catalog/baju-jersey.png",
    specs: ["Untuk pasukan sukan", "Boleh tambah nama dan nombor"],
  },
  {
    id: "baju-sublimation",
    code: "BJK-010",
    name: "Baju Sublimation",
    category: "Sukan & Sublimation",
    price: 0,
    priceLabel: "Harga ikut design",
    image: "/images/catalog/baju-sublimation.png",
    specs: ["Full print", "Sesuai untuk jersey, event, dan team wear"],
  },
  {
    id: "baju-singlet",
    code: "BJK-011",
    name: "Baju Singlet",
    category: "Sukan & Sublimation",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/baju-singlet.png",
    specs: ["Ringan dan selesa", "Sesuai untuk larian dan aktiviti sukan"],
  },
  {
    id: "baju-f1",
    code: "BJK-012",
    name: "Baju F1",
    category: "Uniform & Workwear",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/baju-f1.png",
    specs: ["Uniform kerja", "Sesuai untuk team operasi dan korporat"],
  },
  {
    id: "baju-f1-muslimah",
    code: "BJK-013",
    name: "Baju F1 Muslimah",
    category: "Uniform & Workwear",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/baju-f1-muslimah.png",
    specs: ["Cutting muslimah", "Sesuai untuk uniform staf wanita"],
  },
  {
    id: "hoodie",
    code: "BJK-014",
    name: "Hoodie",
    category: "Uniform & Workwear",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/hoodie.png",
    specs: ["Sesuai untuk merch", "Boleh tambah logo atau design"],
  },
  {
    id: "windbreaker",
    code: "BJK-015",
    name: "Windbreaker",
    category: "Uniform & Workwear",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/windbreaker.png",
    specs: ["Jacket ringan", "Sesuai untuk event dan outdoor"],
  },
  {
    id: "jaket-korporat",
    code: "BJK-016",
    name: "Jaket Korporat",
    category: "Uniform & Workwear",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/jaket-korporat.png",
    specs: ["Gaya korporat", "Sesuai untuk staf dan program rasmi"],
  },
  {
    id: "apron",
    code: "BJK-017",
    name: "Apron",
    category: "Uniform & Workwear",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/apron.png",
    specs: ["Sesuai untuk F&B", "Boleh tambah logo bisnes"],
  },
  {
    id: "chef-wear",
    code: "BJK-018",
    name: "Chef Wear",
    category: "Uniform & Workwear",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/chef-wear.png",
    specs: ["Uniform dapur", "Sesuai untuk restoran dan katering"],
  },
  {
    id: "vest",
    code: "BJK-019",
    name: "Vest",
    category: "Uniform & Workwear",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/vest.png",
    specs: ["Sesuai untuk event crew", "Boleh tambah logo jabatan atau team"],
  },
  {
    id: "safety-vest",
    code: "BJK-020",
    name: "Safety Vest",
    category: "Uniform & Workwear",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/safety-vest.png",
    specs: ["Untuk keselamatan kerja", "Sesuai untuk tapak projek dan event"],
  },
  {
    id: "topi",
    code: "BJK-021",
    name: "Topi",
    category: "Kelengkapan",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/topi.png",
    specs: ["Cap custom", "Sesuai untuk event, merch, dan uniform"],
  },
  {
    id: "bucket-hat",
    code: "BJK-022",
    name: "Bucket Hat",
    category: "Kelengkapan",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/bucket-hat.png",
    specs: ["Merch dan outdoor", "Boleh tambah logo"],
  },
  {
    id: "lanyard",
    code: "BJK-023",
    name: "Lanyard",
    category: "Kelengkapan",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/lanyard.png",
    specs: ["Untuk event dan staff pass", "Boleh custom design"],
  },
  {
    id: "canvas-bag",
    code: "BJK-024",
    name: "Canvas Bag",
    category: "Kelengkapan",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/canvas-bag.png",
    specs: ["Tote bag canvas", "Sesuai untuk gift dan merch"],
  },
  {
    id: "non-woven-bag",
    code: "BJK-025",
    name: "Non Woven Bag",
    category: "Kelengkapan",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/non-woven-bag.png",
    specs: ["Beg ringan", "Sesuai untuk event dan promosi"],
  },
  {
    id: "umbrella",
    code: "BJK-026",
    name: "Umbrella",
    category: "Kelengkapan",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/umbrella.png",
    specs: ["Payung custom", "Sesuai untuk corporate gift"],
  },
  {
    id: "wind-flag",
    code: "BJK-027",
    name: "Wind Flag",
    category: "Kelengkapan",
    price: 0,
    priceLabel: "Harga ikut kuantiti",
    image: "/images/catalog/wind-flag.png",
    specs: ["Untuk promosi luar kedai", "Boleh custom artwork"],
  },
];

export type ProductSort = "name" | "price-asc" | "price-desc";

export function getCatalogueProduct(id: string) {
  return catalogueProducts.find((product) => product.id === id);
}
